---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.secretName }}
  namespace: loki
spec:
  encryptedData:
    admin-user: AgAJwEV/dzyqYV11NBjEUB6sNZOSQTCHGj4XR0zL3srMNK4k9YTetpbj9E+DwfC3J05qTVxxyxRKzVy9oYqIHysomnxTxUU1sSDmIMGB9l353NjVT8J8h2U5sVDwdq6HVDnbLfw4JqV8m5CAOv3EzZPROFqgItJXuYKklVoMMUIQF874MshRC9+BTE27RI02eRX9gh7vpYCIfU2GLSMWmMtehj4F5fdMNGbSDeo/DX5j4soSLMrQ3EJ0MkqsTymNOncOb0dfn7kNoouNUjz98elce+F0s5AlASuEB9iF7EovyMsjkWQDDT3M1Gz3ep2+3W4lD+PrZ/+9Hmn4+HcZYfFam86VFf9zkrHWm7RwaDdjcEcbZlpSl0dARfjCUghWFFYkfdfRVPwracH4gNEVXOQ7CXBDtAQB8da+aI58/u4/OCTPb21ohpLZ7UJAy6cdVM2CL9LbcU46wOunlgrkJpFmLikWIBx4y4scrtv0VLqT+/Njdsc4XGDLuZWcvMHRQe+pAWXNTk4qtK7Z3jZICjhz0RlNt9jsG5fRtZE0iO8LuHD26kl/NacUNRo4K3nAOJYHlJSR25hQSKPd4MKAyZ8gR0bKFE9vnl50gsRFSfRt/kxDsDRcxud5UaKCL/Byzpfw0K3lPc4jcWdkTOVb4rb2hipzaO6kQVXy1OvcT12/97E8qk6pF1OvsHrb4e6gcXCixGKtsg==
    admin-password: AgA27iJL0qZmXzGpLDiiGkVrTyH/Yya2MeyV5tqXuPaHJX+p6BJaArHgoJS0S9fdm0Y4sBYOkWv6NU7NXSm+jIbRJ21kxsjr648qVbBHY+94i7gfadq6yjKFpoWw91pVgywda9H6/H77JcDqyIEdbcn3xSVI3n8W/uzQ6P7/bPXzuBpG9oF34MEPkW9nxhi4/Y3cbQOPkmxUm101sgyKRWJ1gfptq6VDu+L+7Vjh38PmahwkMBRZqNCPeUeTViVe+F34rdvRSIq1A7dNAEhiC/3f30vWOj4gp1caeQPF/zHRY6zlY9KmXprQUonRKwvrU1WpQduFELFsvpFcco5aFwJB1a/RKmWrul2sufU06aG49c49/YWKiUB4hHeM97FIbGcCPc8GWYQzFG27V+FmN6PZsk7pmDxp/scUn8yavahugxBVVOq1eSIM0LhO+do/ZLNdeB1bDiUttP40NE9AlXTznL0HJUbEWJQib9Yzr0z1vF+5CKd04COB2WfvXHk5QdrwRasngNW9xZQ8oc5GWbIyiQ3Rx72As8mquKWIpyFI4czLy5re+u4NNUf1YgeArG4KMPmuWTyrt2SFFwngPzeUtI/RrAZl+6NFVMFMncDrVglRw6wMuSjv5B0CSLLAGrOr85Ce3nJkj6yljpg0WOKrptS2HDR79f1xyk1OJHsgoFNNthz0vQToa6l+ibB735s=
  template:
    metadata:
      name: {{ .Values.secretName }}
      namespace: loki
    type: Opaque
