---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.secretName }}
  namespace: loki
spec:
  encryptedData:
    admin-user: AgCm2KzOkI9R9T2IFm1EFCAcFNaAanfRIZE0+RBz3sp1ZJf5fIQT+7S0NUh7w4dxHXbEYbcvz4Xr0UhruIfjkqPUV55wMRGiY8rmcXMe+3gKOqNln6XFvTlvsCGybY+aaJhoEs+Cd5Q4T/R7UuGlf7CBfmryIbsF4ZGxo52qw1SoalVAAQxMQOd+PAQ/1RYQuUxyTYsgTbCfnhGCjHbt5r9s3YdUTV+wnUV/3v0EuFrHzSxbKfecRpztGiYnn6wdO3zMKAYnQRWBwzAb7jZVcD5OdeMtgi/W+5WP/VTqH6uoLbfifsuI/ltSRg0rdegG7f9XNkTy4idDRD7+RX/xq8XdGiM1aOsoePe8NWsw7BloR93Sa8AS4KSHIEVW6MJC5VK02W7rhXKBYuIC3Qcydt6FtLQgWSrBT3hN7NDzbl4WwZMK2PPLJXRH1m+wOybAEGyVmaD0cpKjBjzIi41n3JNgz26EHwN8v/PoXOG0O2rii0fSrNJKAiaTPflYtv/hG5mw+85Om1VHObS2hRduR/2qhszBRS6kz4d5Dsb8Y8q3Gxim2827S1cPApjQ3VyBgY8Pm7q5rp5kh+dP6YC+diy/Cyetm9LX8Jhilj9ygaxZUyfg3Q0BMQiE0kivcl41cfbxRkR6cePaFXIIKVLUPienWEivWv09keStQ7IWydMv3J7wlt5WeoNwQrkzH9PPY2PzBqFAUg==
    admin-password: AgAdgF0OG7tBxQAZpiBcN3x/cNkiGam5CFi+uheia+MiRs422LBibgyznY8CDrrwtDnQlvQSJo6NseRes8pjWSH40LlpbZx2sZyKWUUZnz9DowjYruzzt9g4+RVp7+5TXdz8TP0TGpNh8031hzF8J0Y72zbmvi2edHUWPJ+BYtKnaPrQjcAhvOYCBEFxqBCK6lr2reFQz3eTobdZmog/CJjzgKBAkEFImbn9orPOJ0sSTt5PU5K7xAoBEIINO9CyG5YbLTeV/wxIsx25PbDHWxRTMxkOGxGRjSIP0xkgkX3OE5qVT+LVKKS34JoC3VPQ97EZ+tfhXUC6u8/6LxEoYw14fUxbqfnCbIDlKHlvuh1BOTfCR7dbkoPLfGYdXdZ8+20pXm8bM0gElDgZ9bgQE81XVytu3AbU02jGL3lAaW4lSIOLukmLp06tW2Xk0sp62kTKhxTbyFVi+/WJsAPEhihCjfmZdyZfZV6QjsOmfr1/ZdspEZ3mEkxUutUZV0lnEmu/kvRQ1p7K7NMy5kia8jJRZkgscptFJS38Iwo+DOeju6QSByYRIh0HELOyrbz8WrF4PA4pkOThKvjnhPIn2y5ywq/ETP40he4hfCp2a321jRnqmSH0Znuct7L7+lVE2gKYF219db53QFlbb4L8dADMe+GhDVkFkwMBnYNONClKh4Oq9mpAY0WMpj6eKT/yR64/lgshGvVR+rn0wd5ElwXuOxb3p12PDf4Z8iVVs3K4TfAdNTiYvUgG
  template:
    metadata:
      name: {{ .Values.secretName }}
      namespace: loki
    type: Opaque
