apiVersion: v2
name: loki
description: Loki + Promtail + Grafana for log aggregation
type: application
version: 1.0.0
appVersion: "2.9.3"
dependencies:
  - name: loki-stack
    version: 2.10.3
    repository: https://grafana.github.io/helm-charts