apiVersion: apps/v1
kind: Deployment
metadata:
  name: roundcube
  labels:
    app: roundcube
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: roundcube
  template:
    metadata:
      labels:
        app: roundcube
    spec:
      containers:
        - name: roundcube
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          env:
            - name: ROUNDCUBEMAIL_DEFAULT_HOST
              value: "ssl://{{ .Values.mail.host }}"
            - name: ROUNDCUBEMAIL_DEFAULT_PORT
              value: {{ .Values.mail.imapPort | quote }}
            - name: ROUNDCUBEMAIL_SMTP_SERVER
              value: "tls://{{ .Values.mail.host }}"
            - name: ROUNDCUBEMAIL_SMTP_PORT
              value: {{ .Values.mail.smtpPort | quote }}
            - name: ROUNDCUBEMAIL_SMTP_USER
              value: "%u"
            - name: ROUNDCUBEMAIL_SMTP_PASS
              value: "%p"
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
