apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-config
  labels:
    {{- include "calibre-web.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.config.storageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.storage.config.size }}