apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-nextcloud-data
  labels:
    {{- include "nextcloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: nextcloud
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.storage.data.storageClass }}
  storageClassName: {{ .Values.storage.data.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.data.size }}

