---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-secrets
  namespace: pubquiz
spec:
  encryptedData:
    admin-password: AgAms8MXEfiFj/vULpuY1QYkcSEk44Qn8XCrbBikVIH9ZspFkELaeb3QJ0uTlKrF94AVgbttIYwAYJd+Dh80Svmy31Me4RMEP0rvGGBsJNGpBY11hskAOov80LgdLsyYUbIXFrIbsKiI1HKnMilYtzvp5gSbS58BpxfSxOK5wvdIJWSIHcZijR6ht+C6hHxHaTLgCZHX9a7yedYz6MDIc3RScGSavMDCoqY136T8FPd6kaKx5IjojiF+znEVqHTm1ZIkEacH4ZQASDSh3/d8AhWq4yI6Y6U6tramzF8m92BWGKRyfMUJ0LyCHDWBi24NB0oQUqyrsXuoGktjXPfWmH0yIxOPxr+R4+7SQk/zwnSWR3yCVUb2Dp9Tl5Uaha1Y25zg4yVX6VUGzKB8loCm9ekfVKd8cdSUtOZKevbgQRQFec4VfmaiHhuAR6TlZ1BiLu0E8CM0A6qPQ2IGv/dxHU++uE3nIV45VHblTO4hfb5KHnKZZbpaxImyFhN8BwGl42xJa/VIzWXdw2nb9PFls99h78gyVS3tHehOyLMSiXPJTzYaqVfbNQbpyqEmVuSf11vVAMfQYbOpRMUDovMAzPrtxi6LQHxf3lw3iZv6rGl+gIFs05U5Psk0D4G3luRq55EUxCYPHbKooEGB9ODQiUoftAT7DNl1PgLXIjAvkPWLYoCxj91M6/xMvXdV4cwS6QiiOvZeP0TnA1CYKmdP/Gk7Q14CEk1JeBcR+yt5JHw7sOyzv8zOpGeG
    postgres-password: AgCtGHPfoxt4eatYmsvE3H+g7PD4rHJlstY+7QdSbvsnoI6Iq9VRxuZvMFXap6jwB1EL5+CO0ZzRi9rrjPqOgzsMPw6zAIW/UYkzuarRvg2h2a9a1SuE457PQ+HM1J1C0hvJajAUJunzJZjMBfo8UCM5D9Dj4h6+RL0OubbR9uSD7V32YzmY+dORm2GpUapJp4hhQjn4i5bQ+ExVoq146X2Kbhuw7UGQbN9izD+Waq13iYUyaW6rdNWqwRvyAZFFAM5dpTNNm7VktsZ0Uvlqh5v6SPUJ1RpdTKaDW+Hdkrt/z7RchLpXQ9bO556NTOoxPPaDBTPJDc2uqLqf1E5VlRn+ubdA2Lwtbqw4chDlyRRxVm9YE+UjnhehTvIGTzQxT6bBV96giLti72rfu08WIHyQjDd4xVFY61MY2mu9pUmkO6+XW/tmShLA6H6u3i2MSFddetqtHhlKZBOrLzcu8gTKGJfZA2WSDZNFpioA5JSDdNxMwR3DdpjuQw5JZbzZzECcBNkpoB/PtyWs/aEhy47ppyN7Drt4u0zJpU9lrmjrVo97zAWw5vsXc4imPg8HGJc7MpELavdUC14nxf27Kj0ftdHWABJVxTZAv+ypvigWNba3Nsph38b0rkWArQUZmq8eJU/E1Y5asvHGGp0WjmWIqacdQS2Fo7EqXAy6C6xXaYlwiVM/xZVDWfkX2fga2kIkC0u7Redd1kfyrftPl9PLxzVp7daXNHxkNouAt/MWJkdQtHZFk8Pw
  template:
    metadata:
      name: nextcloud-secrets
      namespace: pubquiz
    type: Opaque
