---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-secrets
  namespace: nextcloud
spec:
  encryptedData:
    admin-password: AgAePABEd8pzGBo0XhgKhTdD7myIou0FOwCHriZPGRazEFtyzwmVo9AIVVYoC8NEHFhIXoVYHXfuJgHbhnjcpZl6C+V0Za157Y3/bsxMC2V7kjFBiEuscSlIfTIrmxiJgxdRgR6jiUxaYe/A2CsoByc1hD7D7gNfEffsjCWWD0vXE0nKJZNsba8prLluMPUQywCtQDils+oFgTN9wsq5ZMO6OAtfahNkK0VDKM5/jvC2MrpwrpFcr5Aa0by+U1P0Ae0Sbd373v9e7RXwLV7Q/qO3Dw983sb7BaHwzXYS0EZSlZM1k4cDLNgm3Ne73YGk9sROi9rf7GHSiAS2CQuO2KM/SjO4mz3FlEtxJB3KEEIbsOySN6NC0CEd1uLe4U2vsNVdUIFYYYbhERLx4jgHYw3fagsQMCQKSlF0I7CEgWS8O/FcwnJL/mO9ZFgQD3CWfogT2Rmq/BAa+T/8FsM09FUeWZAiG+Uk1C5TDtA5ZY8mNcIpMAQJVPIriqzh7+UKI1fp0BzASeTVP2K91fDkJf9MfbtMVY6Opcn9S9KQKfAHgx7g25tZ5QUdqVnmQ26tnVu37A+qqDsHainaqpZlCgz2CTivofifO+02lCB+6RrD9VQyolNAAl+uL/A74vrNLtcI329fVVKeh0sNkkxu0DDgIe5hqdNZ5XndBhr68fBCxYQZHvgFjqFHTyvfari2GO16xAyqiHVqSpVhepUybdejznqhSBwBaq6hNv/QN5NFmwBkV26zW7Zs
    postgres-password: AgAl26cG6N6c6IjYd4edvZlOmZJhpjge9KxeA5UsbLr0rt5OxuBSMv1gaTQ8FVt4LkGL9sqqDP6UqP0aL7AZONY+mB7g305v7XZSHnvRqGyfRgCn2uwEsfl7Oa4CXz+j5LyTYhyl38XOmHOXr7R07M31g1JOOeQJLTKY/9X5UCbJ7GwXwiP0YKtZGNRyAG/ybTTNbF2kb/xoKebKvemrNl4Je+xjW/Xu5QtTvZQmxwgpyP8OSIcFllEHoWBdyYd5zeNxl2Z+OV9vyZYZAVTDXkDiYJK3iZpSdSgnrDD0z/r5qnmzqhaPOIK7wQ1rJFt7net4YVbSBLSNvu2FSmo3yb+H9lqCJXUPo7q5SeMqBnnqweyZpDpbTctcqUAwP/jmbs28ifAcaA2k30hHMAY9UHklj0yYxMr+WGQDSDvFfE6FWV/FBoo1GJZ7ujRYNXPlPNcyylXCy3zMIIxeyLdVKOgHGCJioMZwQ2oDVMbU9RxSrf0BWdG9pQ6hvUndw+9rFNN1Rg3UCPDxftpxVjbjt9Ii54jJfTKF4tzgI0IXIsKTdoFjnvAkOTeNOUW55JigEFr7mMr4gMee6oa7d+DZ1XXanOirjVgH2AVN0SQ6gXejU/WVtv4hvqpRR2aPtX9IfWG5dlQ7Fdzw6TIVnOKsIbLK6TZWd1EQf99trjxOA8FZr6BldFSdOO/tk9e9zg21Qvs8/Tkh9mv91Rlom/i8X+ly4HL3bFKC/Er3ON9FrImEjGsSsINNxvz9
  template:
    metadata:
      name: nextcloud-secrets
      namespace: nextcloud
    type: Opaque
