---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
spec:
  encryptedData:
    email-password: AgCc49Edmoq1HEg/kNiJI2yUijKEso/CAusdLZkfH/rglohWpm+XlxwlNaEEV/CFFZNbhAPD84T1wiNI1Nv3hLVelcjZxaYWssxelGUo5lf65FV+WKPKsKKAgMVfB5KS7jMgZOkc4Fr7h3QDxzMQs/5pD5yFmbU9DnJXdxAqCUbLj2FZ6xbtQ0/AsoTCO3AkUrD7PnvGBVJ+H0B6WU3PkaONagt/SNRKdVRRwNsVdr6a4GNPD7Abaz8UQ5PqevQdOjVgUei/0QS95zBNVltqR6iSyqIX1Yg0+1Q8spiqlEj5rtnsPnssFgUVYo5lGBif/jHw0fnxPhYtNCZvvb92/WHmhQHJOTAKdPOz4V2jbIA2txwkp2fLDu3Q1WvhZc7NSG0TF17HwjCXWMghq7/oPvVdX9eynhKO/G8Isz5gZvieYAAtJh45DeybgR2ftKs900j/z3t2Ry+kQ0lYvWYzsSB7OLByvSSw55xQXpHOVQiYeOcBiDp+824lz87me0C9yl5PjiVP9dK7jWF+3SbwwUjcVf9+UBDUmBJYhLhq3TpkxYd4O1uoUxGBYlsm2OVXPGHrqzK4QqMfO1CpZHxvqlTI0zBzVT0w2vUsNkpIaG2XHHSAMgIZWffnJmVcSlCR2BRXprM/dTaOIICMlnbieTLUq01RQgR5eZKPtS7VJo1hLuyySscMzXzw5h51APq27YqYxBqmA5XQ/E06K6eSnaal2aCCdQgRKMqGMQcJb2aawXrhuRg=
    email-username: AgB+l6s8FyPqW+8urWGS7iap9tyGCxALKN+VJOa7O4kMHLNEV6/c50aABZujvT8tLpkhh/L+DtoxrQB/d08FfBJ5FTh5x13zf4a5bm8uGRjUo5FiAZYYCxb6Pstu/rtlZO3Ao1xMp6quAbpiwz0GCg096twdVTwjLsXSBVhAUuYYQBw6myI9On+hTHSyjHklHrnuW0UXiUYG3ISXooEmaq7mqgPY7Dkiz59fx22k1YAzvuehEg649pvZZ6rPSPR77SLBKK/EJ2u/0DZ/OxpRKBEmIYJ1JVyZD3iGO8Is51A9LgS24a7V/FbCMuUk6pBLEw0SD8AQwwKu/4ivSF10CGY0/p38eAZMnXMf5PyYmJGlTrT+UQ9JLBIzX76dDOH7DxACJPRS/89hbfGCrpBOgd0aS5SKLzI2niIl1PuT02CDtX6VvftuP0vdxl/efu+AkMTkTlhBZvKvSz2PdWVcM8FA3DxuhtY1ZKlSobpxUbFTeXN9xaEQFJlBMLQ/t9aaTD9cq2XvkqbSsw3k6avXWFs31fjGVGjm8P6q+AE+5qPg56tN2j1ylctYzDHCx9N7S3hHxpa7nK1Cej20hPQeOc2k9DxVsTdqA4ycPP3RXrPQss/AYmu+hltp2qQkQyQOA4m8ZamlRHYzLMznNOFWAr6Y5vXEu9qqxIgKB351SSpTLhQ1/7i4MFUsMqzXR0wt5SKZysC4dEw=
  template:
    metadata:
      name: argocd-notifications-secret
      namespace: argocd
    type: Opaque
