apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
spec:
  encryptedData:
    email-username: REPLACE_WITH_SEALED_VALUE
    email-password: REPLACE_WITH_SEALED_VALUE
  template:
    metadata:
      name: argocd-notifications-secret
      namespace: argocd
    type: Opaque
