---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
spec:
  encryptedData:
    email-password: AgCHWs8T3QljveUp1On2EdRywpIoKXLqQDFZZYRJ4ng8ewxU0ao5tUNkxmGINJwO+3YE/CNdhfdnV7C2oe83xYsgEMANkidCJxaTlxX/7lMe4ihh1WWtUFwQPl3XqZEQsxVy5IackHpuvp5vjx82nN78093uJtD4ul9mTlEIQF+I+l6pPgEjsuxh9Rh8yTSgftWTVinvdW4i5ROateslPEKOqUU3XiTJDieN5wZY0Ihsd93D64vz5+kwXAbwEkT2ckbGdiUtdpxEsphNUb4HZC8pO5HvCYMmLuM5NPxW9KyzbCjyzPf7iXJPVFV0a62ik2g3zzFLdA8dSTZmp5KwowUqcf5v6nviJy0DF+EnHHNSe9HKda2Xk8J0CouunRGsItDrdj87YLnM0nElGtWOzSoFN7CtCJOBy9/OzSdyuD4o81mqYPcz0kACz8Ka6E6XmFKxnwUpbXfZHIPvhGALSiJMerE1E9M9FAr6LKSy68Tpz9eW0qzElQE+8tpSFz+dIWhh5Xql7W/pwb1YcUjOHWPeQUk5T4mCayvuNLhVLkww+AsgKPvKZKXniHNNerCQ799PGIjexYVlU4TITRWwttu2QBf7h7YJQg50asbnJrhvp04PiqsdNTVvNi6/OH4WpAV+JCYRTOG5hvuwLfQhk4TTrwCf45//EFI/saMpFrorMV3Mc9OezYTqHBio/S762rC/rMm8h7/fKNJsRj0nP68j+cnE2T0d55VqDcyHyVZakLJvm6U=
    email-username: AgBYBAsVav5v6I0kWvIWR5nLw2LswCbCr4kcDW+WcXDmKzj3fGjZwhHWcPe9A6A/ugaGx2ZQrdOqQciOMKiFu7KjQCfV3T1lthvAqthKLNKl0SYWiidb9ljTH5aRNkO7EO+Mp2VThTlslxpG6x0uuNX+ZQRAfNmq9swjmTlGSLMESYtwijla5CbUiphGcDAmpjbfxqOi40H5vgKLGAczaoqXe2YiqBTsfKHelR4KVkSkKTamAdbfTuYQbcTKBEjifqpfk2ku+dz4Zpxa7QdwXSQH8RzgjPIl3B2oRmdW7MtfZHotR60faz/xBN1X1rCLEAm+/PoJPQdj7i2HEfBNfXfNXcqnwyfxGHLgrD8IIjyj3+R6V3OJRZ6nFKUE61IEK67ZW4JBCl1poZ23lO032eyw9/DX4idRo00esO7keZsOSmcgmkqBYZR7E9u+Aqq2thInfk5ofNLiSGjyJ8lYrDPrBvaS8OY7rV/mSiLipC9hEvdh+Eg8tEx675fSkdHNsWwW/RaoU99MnfJO4We39piYxhiYb59E6FZnCjCmCvf4zHg+bi8pJukhlU6GIWMluPtpB2IOR5u8hVDAbe4GsFu1CynU7cpL9bAWLLlFNngE21F1jtXPodIci/EUcOeb2iJxIPyn/6uVPYhWdyHL2qqK7EKPTTJeRsKy5OydARTGmLM96Nfr00A3kzYnH2SsP7vhsBvpFvE=
  template:
    metadata:
      name: argocd-notifications-secret
      namespace: argocd
    type: Opaque
