apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apache-passthrough
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - danilenko.io
      secretName: danilenko-io-tls
  rules:
    - host: danilenko.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: apache-external
                port:
                  number: 8080
